<#
.SYNOPSIS
    Exports WARA analysis results to CSV and HTML formats.

.DESCRIPTION
    This function takes the Excel file generated by Start-WARAAnalyzer and exports the data to CSV and HTML formats
    that can be used in a CI/CD pipeline without requiring Microsoft Office.

.PARAMETER ExcelFile
    Path to the Excel file generated by Start-WARAAnalyzer.

.PARAMETER OutputDirectory
    Directory where the output files will be saved. Defaults to the current directory.

.PARAMETER CustomerName
    Name of the customer for the report.

.PARAMETER WorkloadName
    Name of the workload being assessed.

.EXAMPLE
    Export-WARAReport -ExcelFile ".\Expert-Analysis-v1-2025-02-04-11-14.xlsx" -CustomerName "Contoso" -WorkloadName "E-Commerce"
#>
function Export-WARAReport {
    [CmdletBinding()]
    param (
        [Parameter(Mandatory = $true)]
        [ValidateScript({ Test-Path $_ -PathType Leaf -Include '*.xlsx' })]
        [string]$ExcelFile,
        
        [string]$OutputDirectory = ".\WARA-Reports",
        
        [string]$CustomerName = "Customer",
        
        [string]$WorkloadName = "Workload"
    )

    # Ensure output directory exists
    $null = New-Item -ItemType Directory -Path $OutputDirectory -Force
    
    # Import required modules
    $importExcelModule = Get-Module -Name ImportExcel -ListAvailable
    if (-not $importExcelModule) {
        Write-Host "Installing ImportExcel module..."
        Install-Module -Name ImportExcel -Scope CurrentUser -Force -SkipPublisherCheck
    }
    
    Import-Module ImportExcel -ErrorAction Stop
    
    # Create timestamp for output files
    $timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $reportBaseName = "WARA-Report-$($CustomerName)-$($WorkloadName)-$timestamp"
    
    # Read the Excel file
    Write-Host "Reading Excel file: $ExcelFile"
    
    try {
        # Export each worksheet to CSV
        $excel = Open-ExcelPackage -Path $ExcelFile
        
        foreach ($worksheet in $excel.Workbook.Worksheets) {
            $sheetName = $worksheet.Name
            $csvPath = Join-Path -Path $OutputDirectory -ChildPath "$reportBaseName-$sheetName.csv"
            
            Write-Host "Exporting worksheet '$sheetName' to CSV..."
            $data = Import-Excel -Path $ExcelFile -WorksheetName $sheetName
            $data | Export-Csv -Path $csvPath -NoTypeInformation -Encoding UTF8
            
            # Generate HTML report for key worksheets
            if ($sheetName -in @('Workload Information', 'Impacted Resources Analysis', 'Platform Issues')) {
                $htmlPath = Join-Path -Path $OutputDirectory -ChildPath "$reportBaseName-$sheetName.html"
                
                $htmlHeader = @"
                <!DOCTYPE html>
                <html>
                <head>
                    <title>WARA Report - $sheetName</title>
                    <style>
                        body { font-family: Arial, sans-serif; margin: 20px; }
                        h1 { color: #0078d4; }
                        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
                        th { background-color: #0078d4; color: white; text-align: left; padding: 8px; }
                        td { border: 1px solid #ddd; padding: 8px; }
                        tr:nth-child(even) { background-color: #f2f2f2; }
                        .header { margin-bottom: 30px; }
                    </style>
                </head>
                <body>
                    <div class="header">
                        <h1>Well-Architected Reliability Assessment</h1>
                        <p><strong>Customer:</strong> $CustomerName</p>
                        <p><strong>Workload:</strong> $WorkloadName</p>
                        <p><strong>Report Generated:</strong> $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
                        <p><strong>Worksheet:</strong> $sheetName</p>
                    </div>
"@

                $htmlFooter = @"
                </body>
                </html>
"@

                # Convert data to HTML table
                $htmlTable = $data | ConvertTo-Html -Fragment -As Table
                
                # Combine and save HTML
                $htmlContent = $htmlHeader + $htmlTable + $htmlFooter
                $htmlContent | Out-File -FilePath $htmlPath -Encoding utf8
            }
        }
        
        # Create a summary HTML file with links to all reports
        $summaryHtml = @"
        <!DOCTYPE html>
        <html>
        <head>
            <title>WARA Report - Summary</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                h1 { color: #0078d4; }
                .report-link { 
                    display: block; 
                    margin: 10px 0; 
                    padding: 10px; 
                    background-color: #f0f7ff; 
                    border-left: 4px solid #0078d4;
                    text-decoration: none;
                    color: #005a9e;
                }
                .report-link:hover { background-color: #e0f0ff; }
                .section { margin: 30px 0; }
            </style>
        </head>
        <body>
            <h1>Well-Architected Reliability Assessment</h1>
            <div class="section">
                <h2>Report Summary</h2>
                <p><strong>Customer:</strong> $CustomerName</p>
                <p><strong>Workload:</strong> $WorkloadName</p>
                <p><strong>Report Generated:</strong> $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")</p>
            </div>
"@

        # Add links to all generated files
        $reportFiles = Get-ChildItem -Path $OutputDirectory -Filter "$reportBaseName-*" | Sort-Object Name
        
        $summaryHtml += "<div class='section'><h2>Available Reports</h2>"
        
        foreach ($file in $reportFiles) {
            $fileName = $file.Name
            $fileDisplayName = $fileName -replace "$reportBaseName-", "" -replace "\.(csv|html)$", ""
            $fileDisplayName = $fileDisplayName -replace "-html$", " (HTML)" -replace "-csv$", " (CSV)"
            $fileDisplayName = $fileDisplayName -replace "([a-z])([A-Z])", "`$1 `$2" # Add space before capital letters
            
            $summaryHtml += "<a href='$fileName' class='report-link'>$fileDisplayName</a>"
        }
        
        $summaryHtml += "</div></body></html>"
        
        $summaryHtml | Out-File -FilePath (Join-Path -Path $OutputDirectory -ChildPath "$reportBaseName-Summary.html") -Encoding utf8
        
        Write-Host "Reports generated successfully in: $OutputDirectory"
        Write-Host "Open $(Join-Path -Path $OutputDirectory -ChildPath "$reportBaseName-Summary.html") to view all reports"
        
        return @{
            OutputDirectory = $OutputDirectory
            SummaryFile = (Join-Path -Path $OutputDirectory -ChildPath "$reportBaseName-Summary.html")
            ReportFiles = $reportFiles
        }
    }
    catch {
        Write-Error "Error generating reports: $_"
        throw $_
    }
    finally {
        if ($excel) {
            $excel.Dispose()
        }
    }
}

export-modulemember -Function Export-WARAReport
